repository_type: pipeline

nf_core_version: 3.2.0

lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - conf/igenomes.config
    - conf/igenomes_ignored.config

template:
  org: bcb-unl
  name: dbcan-nf
  description: Automatic and standard workflow for CAZyme and CGC analysis including
    abundance andvisulization in microbiome data
  author: Xinpeng Zhang; Haidong Yi; Jinfang Zheng; Yanbin Yin
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - igenomes
  is_nfcore: true
